name: build-images

on:
  schedule:
    # build every Friday at 17:00
    - cron: "0 17 * * 5"
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [universal, bootstrap, ci]

    permissions:
      # https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#publishing-a-package-using-an-action
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check for changes
        id: changed_files
        uses: tj-actions/changed-files@v45
        with:
          files_yaml: |
            images:
              - ${{ matrix.image }}/Dockerfile

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        if: steps.changed_files.outputs.images_any_changed == 'true' 
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/${{ github.repository_owner }}/homelab/${{ matrix.image }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha            
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        if: steps.changed_files.outputs.images_any_changed == 'true' 
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        if: steps.changed_files.outputs.images_any_changed == 'true' 
      
      - name: Login to GHCR
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request' && steps.changed_files.outputs.images_any_changed == 'true' 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        if: steps.changed_files.outputs.images_any_changed == 'true' 
        with:
          platforms: linux/amd64,linux/arm64
          file: 'images/${{ matrix.image }}/Dockerfile'
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}